# Generated by Django 3.0 on 2024-08-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://alllocal.ca/wp-content/uploads/2020/11/food-placeholder.png', max_length=500),
        ),
    ]
